x-env:
  environment: &env
    POSTGRES_PASSWORD: test
    POSTGRES_USER: user
    POSTGRES_DB: test_db

services:
  postgres:
    image: postgres:14-alpine
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      <<: *env

  spring:
    image: goldenkoopa/sms:latest
    depends_on:
      postgres:
        condition: service_started
    ports:
      - 8080:8080
    environment:
      SECRET: secret
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      << : *env
