spring:
  application:
    name: Stock Management System
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test_db
    username: user
    password: test
  jpa:
    hibernate:
      ddl-auto: update
server:
  error:
    include-message: ALWAYS


