spring:
  application:
    name: Stock Management System
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test_db
    username: user
    password: test
  jpa:
    hibernate:
      ddl-auto: update
      multiTenancy: SCHEMA
      tenant_identifier_resolver: com.sms.stockmanagement.project.multiTenant.TenantIdentifierResolver
server:
  error:
    include-message: ALWAYS


secret: testsecret